### PR TITLE
Changes for platform-configs k8s-cluster-oci-new module

### PR DESCRIPTION
**Pull request by wayneyu**

### CODE REVIEW

**Review by jackmw — COMMENTED** [review]
i don't think you need to clone repo? how about just add this file to inside `infra/terraform/k8s-cluster-oci-new/modules`? 
cc @bpoland or do you think forking repo is easier?

**Comment by wayneyu** [comment]
> i don't think you need to clone repo? how about just add this file to inside `infra/terraform/k8s-cluster-oci-new/modules`? cc @bpoland or do you think forking repo is easier?

What file are we talking about here?

**Comment by wayneyu** [comment]
> > i don't think you need to clone repo? how about just add this file to inside `infra/terraform/k8s-cluster-oci-new/modules`? cc @bpoland or do you think forking repo is easier?
> 
> What file are we talking about here?

Forking the repo will also allow us to sync with their changes and add ours without having to manually update platform-configs, except for the tag.

**Comment by bpoland** [comment]
I would be in favour of forking the repo. Or open a PR against theirs and try to get it merged?

**Comment by wayneyu** [comment]
> I would be in favour of forking the repo. Or open a PR against theirs and try to get it merged?

There're a few changes that are only specific to us. They didn't make certain modules like autoscaler configurable through variables unfortunately, so some of the changes are just modifying their hardcoded configuration.

**Comment by jackmw** [comment]
all right. let's do this then. and i'll talk to Tony about pushing changes to their repo to make things more configurable

**Review by jackmw — APPROVED** [review]

**Pull request merged**
